spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employeedata?useSSL=false
        username: root
        password: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: update
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    data:
        elasticsearch:
            url: localhost:9200
            repositories:
                enabled: true
            #uri: http://${CLUSTER_NAME:localhost}:9200/
            uri: http://localhost:9200/
            search: _search